backend:
  name: github
  repo: sedensoftware/sedensoftware.github.io  # GitHub repo adını yaz
  branch: main

publish_mode: simple

media_folder: "images/uploads"  # Görsellerin yükleneceği yer
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Tarih", name: "date", widget: "datetime" }
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "projects"
    label: "Projeler"
    folder: "projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Proje Adı", name: "title", widget: "string" }
      - { label: "Açıklama", name: "body", widget: "markdown" }
      - { label: "Bağlantı", name: "url", widget: "string", required: false }